name: nature_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+4
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^0.13.6
  flutter_animate: ^4.2.0
  image_picker: ^1.0.4
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/plant_names.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
